-- manifest_daralet.lua
-- All entries use propKey (string) instead of propId.
-- The Daralet metatables make InqXxx(item, "StringName") work transparently.

local C = require("item_category").Category

local M = {}

-- ── Armor skill mods (ArmorXxxMod floats, IDs 20001–20023) ───────────────────
M.armor_mods = {
  { label="War Magic Bonus",       pretext="Bonus to War Magic Skill: +",    posttext="%%",
    propKey="ArmorWarMagicMod",    propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Life Magic Bonus",      pretext="Bonus to Life Magic Skill: +",   posttext="%%",
    propKey="ArmorLifeMagicMod",   propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Attack Bonus",          pretext="Bonus to Attack Skill: +",       posttext="%%",
    propKey="ArmorAttackMod",      propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Physical Defense Bonus",pretext="Bonus to Physical Defense: +",   posttext="%%",
    propKey="ArmorPhysicalDefMod", propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Magic Defense Bonus",   pretext="Bonus to Magic Defense: +",      posttext="%%",
    propKey="ArmorMagicDefMod",    propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Dual Wield Bonus",      pretext="Bonus to Dual Wield Skill: +",   posttext="%%",
    propKey="ArmorDualWieldMod",   propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Two-Handed Bonus",      pretext="Bonus to Two-handed Combat Skill: +", posttext="%%",
    propKey="ArmorTwohandedCombatMod", propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Run Bonus",             pretext="Bonus to Run Skill: +",          posttext="%%",
    propKey="ArmorRunMod",         propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Thievery Bonus",        pretext="Bonus to Thievery Skill: +",     posttext="%%",
    propKey="ArmorThieveryMod",    propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Shield Bonus",          pretext="Bonus to Shield Skill: +",       posttext="%%",
    propKey="ArmorShieldMod",      propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Perception Bonus",      pretext="Bonus to Perception Skill: +",   posttext="%%",
    propKey="ArmorPerceptionMod",  propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Deception Bonus",       pretext="Bonus to Deception Skill: +",    posttext="%%",
    propKey="ArmorDeceptionMod",   propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Max Health Bonus",      pretext="Bonus to Maximum Health: +",     posttext="%%",
    propKey="ArmorHealthMod",      propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Health Regen Bonus",    pretext="Bonus to Health Regen: +",       posttext="%%",
    propKey="ArmorHealthRegenMod", propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Max Stamina Bonus",     pretext="Bonus to Maximum Stamina: +",    posttext="%%",
    propKey="ArmorStaminaMod",     propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Stamina Regen Bonus",   pretext="Bonus to Stamina Regen: +",      posttext="%%",
    propKey="ArmorStaminaRegenMod",propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Max Mana Bonus",        pretext="Bonus to Maximum Mana: +",       posttext="%%",
    propKey="ArmorManaMod",        propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Mana Regen Bonus",      pretext="Bonus to Mana Regen: +",         posttext="%%",
    propKey="ArmorManaRegenMod",   propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.ARMOR, C.CLOTHING } },

  { label="Ward Level",            pretext="Ward Level: ",                   posttext="",
    propKey="WardLevel",           propType="IntValues",
    widget="int", ops={">=","<=",">","<","=="}, default=0,
    categories={ C.ARMOR, C.JEWELRY } },
  
  { label="Sockets",       pretext="Sockets: ",    posttext="%%",
    propKey="JewelSockets",    propType="IntValues",
    widget="int", ops={">=",">"}, default=0,
    categories={ C.ARMOR, C.CLOTHING, C.JEWELRY } },

  { label="Weight Class",          pretext="Weight Class: ",                 posttext="",
    propKey="ArmorWeightClass",    propType="IntValues",
    widget="enum",
    enumTable={ [1]="Cloth", [2]="Light", [4]="Heavy" },
    ops={">=","<=",">","<","=="}, default=2,
    categories={ C.ARMOR } },

  { label="Resource Penalty",      pretext="Penalty to Stamina/Mana usage: ",posttext="%%",
    propKey="ArmorResourcePenalty",propType="FloatValues",
    widget="float", ops={"<=","<"}, default=0.0,
    categories={ C.ARMOR } },
    
}

-- ── Weapon mods (WeaponXxx floats, IDs 20015–20017, 20047–20049) ─────────────

M.weapon_mods = {
  { label="War Magic Bonus",         pretext="Bonus to War Magic Skill: +",      posttext="%%",
    propKey="WeaponWarMagicMod",     propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.WEAPON_MELEE, C.WEAPON_MISSILE, C.WEAPON_WAND } },

  { label="Life Magic Bonus",        pretext="Bonus to Life Magic Skill: +",     posttext="%%",
    propKey="WeaponLifeMagicMod",    propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.WEAPON_MELEE, C.WEAPON_MISSILE, C.WEAPON_WAND } },

  { label="Restoration Bonus",       pretext="Healing Bonus for Restoration Spells: +", posttext="%%",
    propKey="WeaponRestorationSpellsMod", propType="FloatValues",
    widget="float", ops={">=",">"}, default=1.0,
    categories={ C.WEAPON_WAND } },

  { label="Physical Defense Bonus",  pretext="Bonus to Physical Defense: +",     posttext="%%",
    propKey="WeaponPhysicalDefense", propType="FloatValues",
    widget="float", ops={">=",">"}, default=1.0,
    categories={ C.WEAPON_MELEE, C.WEAPON_MISSILE, C.WEAPON_WAND } },

  { label="Magic Defense Bonus",     pretext="Bonus to Magic Defense: +",        posttext="%%",
    propKey="WeaponMagicalDefense",  propType="FloatValues",
    widget="float", ops={">=",">"}, default=1.0,
    categories={ C.WEAPON_MELEE, C.WEAPON_MISSILE, C.WEAPON_WAND } },

  { label="Ward Cleaving",           pretext="Ward Cleaving: ",                  posttext="%% ignored",
    propKey="IgnoreWard",            propType="FloatValues",
    widget="float", ops={"<=","<"}, default=1.0,    -- lower = ignores more
    categories={ C.WEAPON_MELEE, C.WEAPON_MISSILE, C.WEAPON_WAND } },

  { label="Stamina Cost Reduction",  pretext="Stamina Cost Reduction: ",         posttext="%%",
    propKey="StaminaCostReductionMod", propType="FloatValues",
    widget="float", ops={">=",">"}, default=0.0,
    categories={ C.WEAPON_MELEE, C.WEAPON_MISSILE } },

  { label="Sockets",  pretext="Sockets: ",         posttext="",
    propKey="StaminaCostReductionMod", propType="IntValues",
    widget="int", ops={">=",">","<","<=","!="}, default=0.0,
    categories={ C.WEAPON_MELEE, C.WEAPON_MISSILE } },
}

-- ── Gear ratings (GearXxx IntValues, IDs 409–504) ────────────────────────────
-- Generated programmatically — all identical shape.

M.gear_ratings = {}

local GEAR_RATING_DEFS = {
  -- { propKey, label, categories }
  -- Attributes
  { "GearStrength",         "Strength Rating",           "*" },
  { "GearEndurance",        "Endurance Rating",          "*" },
  { "GearCoordination",     "Coordination Rating",       "*" },
  { "GearQuickness",        "Quickness Rating",          "*" },
  { "GearFocus",            "Focus Rating",              "*" },
  { "GearSelf",             "Self Rating",               "*" },
  -- Combat
  { "GearLifesteal",        "Sanguine Thirst",           "*" },
  { "GearStaminasteal",     "Vigor Siphon",              "*" },
  { "GearManasteal",        "Ophidian",                  "*" },
  { "GearSelfHarm",         "Blood Frenzy",              "*" },
  { "GearRedFury",          "Red Fury",                  "*" },
  { "GearYellowFury",       "Yellow Fury",               "*" },
  { "GearBlueFury",         "Blue Fury",                 "*" },
  { "GearThreatGain",       "Provocation",               "*" },
  { "GearThreatReduction",  "Clouded Vision",            "*" },
  { "GearElementalWard",    "Prismatic Ward",            "*" },
  { "GearPhysicalWard",     "Black Bulwark",             "*" },
  { "GearMagicFind",        "Seeker",                    "*" },
  { "GearBlock",            "Stalwart Defense",          "*" },
  { "GearItemManaUsage",    "Thrifty Scholar",           "*" },
  { "GearThorns",           "Swift Retribution",         "*" },
  { "GearVitalsTransfer",   "Tilted Scales",             "*" },
  { "GearSelflessness",     "Selfless Spirit",           "*" },
  { "GearFamiliarity",      "Familiar Foe",              "*" },
  { "GearBravado",          "Bravado",                   "*" },
  { "GearHealthToStamina",  "Masochist",                 "*" },
  { "GearHealthToMana",     "Austere Anchorite",         "*" },
  { "GearExperienceGain",   "Illuminated Mind",          "*" },
  { "GearCompBurn",         "Meticulous Magus",          "*" },
  { "GearPyrealFind",       "Prosperity",                "*" },
  { "GearNullification",    "Nullification",             "*" },
  { "GearWardPen",          "Ruthless Discernment",      "*" },
  { "GearHardenedDefense",  "Hardened Fortification",    "*" },
  { "GearReprisal",         "Vicious Reprisal",          "*" },
  { "GearElementalist",     "Elementalist",              "*" },
  { "GearToughness",        "Toughness",                 "*" },
  { "GearResistance",       "Resistance",                "*" },
  -- Elemental damage
  { "GearBludgeon",         "Skull-cracker",             "*" },
  { "GearPierce",           "Precision Strikes",         "*" },
  { "GearSlash",            "Falcon's Gyre",             "*" },
  { "GearFire",             "Blazing Brand",             "*" },
  { "GearFrost",            "Bone-chiller",              "*" },
  { "GearAcid",             "Devouring Mist",            "*" },
  { "GearLightning",        "Astyrrian's Rage",          "*" },
  { "GearHealBubble",       "Purified Soul",             "*" },

  --[[-- Banes
  { "GearSlashBane",        "Swordsman's Bane",          "*" },
  { "GearBludgeonBane",     "Tusker's Bane",             "*" },
  { "GearPierceBane",       "Archer's Bane",             "*" },
  { "GearAcidBane",         "Olthoi's Bane",             "*" },
  { "GearFireBane",         "Inferno's Bane",            "*" },
  { "GearFrostBane",        "Gelidite's Bane",           "*" },
  { "GearLightningBane",    "Astyrrian's Bane (armor)",  "*" },
  ]]
}

for _, def in ipairs(GEAR_RATING_DEFS) do
  local propKey, label, cats = def[1], def[2], def[3]
  table.insert(M.gear_ratings, {
    label    = label,
    pretext  = label .. ": ",   posttext = "",
    propKey  = propKey,         propType = "IntValues",
    widget   = "int",           ops      = {">=",">","=="},
    default  = 0,               categories = cats,
  })
end

M._additionalProperties = {
  BoolValues = {
    [131]="UseArchetypeSystem",
    [132]="OverrideArchetypeXp",
    [133]="OverrideArchetypeHealth",
    [134]="OverrideArchetypeStamina",
    [135]="OverrideArchetypeMana",
    [136]="OverrideArchetypeSkills",
    [137]="BossKillXpReward",
    [138]="ArmorPatchApplied",
    [139]="UseLegacyThreatSystem",
    [140]="OverrideVisualRange",
    [141]="AffectsOnlyAis",
    [142]="ExamineItemsSilently",
    [143]="TakeItemsSilently",
    [144]="DungeonLockout",
    [145]="CannotBreakStealth",
    [146]="CampfireHotspot",
    [147]="MutableQuestItem",
    [148]="StruckByUnshrouded",
    [149]="MenhirManaHotspot",
    [150]="UseNearbyPlayerScaling",
    [151]="IsBankContainer",
    [152]="ShroudKillXpReward",
    [153]="IsPlayerTierChest",
    [154]="UpgradeableQuestItem",
    [155]="FellowshipRequired",
    [156]="SpecialPropertiesRequireMana",
    [157]="RepeatConfirmation",
    [158]="SilentCombat",
    [159]="ReturnHomeWhenStuck",
    [160]="ResetFromHotspot",
    [161]="JewelAlternateEffect",
    [162]="JewelSocket1AlternateEffect",
    [163]="JewelSocket2AlternateEffect",
    [164]="JewelSocket3AlternateEffect",
    [165]="JewelSocket4AlternateEffect",
    [166]="JewelSocket5AlternateEffect",
    [167]="JewelSocket6AlternateEffect",
    [168]="JewelSocket7AlternateEffect",
    [169]="JewelSocket8AlternateEffect",
    [170]="JewelSocket9AlternateEffect",
    [171]="JewelSocket10AlternateEffect",
    [172]="NoRotCorpse",
    [173]="CreatureArmorEffectsDamageReduction"
  },
  FloatValues = {
    [172]="LootQualityMod",
    [173]="KillXpMod",
    [174]="ArchetypeToughness",
    [175]="ArchetypePhysicality",
    [176]="ArchetypeDexterity",
    [177]="ArchetypeMagic",
    [178]="ArchetypeIntelligence",
    [179]="ArchetypeLethality",
    [180]="BossKillXpMonsterMax",
    [181]="BossKillXpPlayerMax",
    [182]="SigilTrinketTriggerChance",
    [183]="SigilTrinketCooldown",
    [184]="SigilTrinketManaReserved",
    [185]="SigilTrinketIntensity",
    [186]="SigilTrinketReductionAmount",
    [187]="WeaponPhysicalDefense",
    [188]="WeaponMagicalDefense",
    [189]="Damage",
    [190]="WeaponAuraDamage",
    [191]="StaminaCostReductionMod",
    [192]="RankContribution",
    [193]="SworeAllegiance",
    [194]="NearbyPlayerVitalsScalingPerExtraPlayer",
    [195]="NearbyPlayerAttackScalingPerExtraPlayer",
    [196]="NearbyPlayerDefenseScalingPerExtraPlayer",
    [197]="SigilTrinketStaminaReserved",
    [198]="SigilTrinketHealthReserved",
    [199]="ResistBleed",
    [200]="ArchetypeSpellDamageMultiplier",
    [20000]="IgnoreWard",
    [20001]="ArmorWarMagicMod",
    [20002]="ArmorLifeMagicMod",
    [20003]="ArmorMagicDefMod",
    [20004]="ArmorPhysicalDefMod",
    [20005]="ArmorMissileDefMod",
    [20006]="ArmorDualWieldMod",
    [20007]="ArmorRunMod",
    [20008]="ArmorAttackMod",
    [20009]="ArmorHealthRegenMod",
    [20010]="ArmorStaminaRegenMod",
    [20011]="ArmorManaRegenMod",
    [20012]="ArmorShieldMod",
    [20013]="ArmorPerceptionMod",
    [20014]="ArmorThieveryMod",
    [20015]="WeaponWarMagicMod",
    [20016]="WeaponLifeMagicMod",
    [20017]="WeaponRestorationSpellsMod",
    [20018]="ArmorHealthMod",
    [20019]="ArmorStaminaMod",
    [20020]="ArmorManaMod",
    [20021]="ArmorResourcePenalty",
    [20022]="ArmorDeceptionMod",
    [20023]="ArmorTwohandedCombatMod",
    [20024]="BaseArmorWarMagicMod",
    [20025]="BaseArmorLifeMagicMod",
    [20026]="BaseArmorMagicDefMod",
    [20027]="BaseArmorPhysicalDefMod",
    [20028]="BaseArmorMissileDefMod",
    [20029]="BaseArmorDualWieldMod",
    [20030]="BaseArmorRunMod",
    [20031]="BaseArmorAttackMod",
    [20032]="BaseArmorHealthRegenMod",
    [20033]="BaseArmorStaminaRegenMod",
    [20034]="BaseArmorManaRegenMod",
    [20035]="BaseArmorShieldMod",
    [20036]="BaseArmorPerceptionMod",
    [20037]="BaseArmorThieveryMod",
    [20038]="BaseWeaponWarMagicMod",
    [20039]="BaseWeaponLifeMagicMod",
    [20040]="BaseWeaponRestorationSpellsMod",
    [20041]="BaseArmorHealthMod",
    [20042]="BaseArmorStaminaMod",
    [20043]="BaseArmorManaMod",
    [20044]="BaseArmorResourcePenalty",
    [20045]="BaseArmorDeceptionMod",
    [20046]="BaseArmorTwohandedCombatMod",
    [20047]="BaseWeaponPhysicalDefense",
    [20048]="BaseWeaponMagicalDefense",
    [20049]="BaseWeaponOffense",
    [20050]="BaseDamageMod",
    [20051]="BaseElementalDamageMod",
  [20052]="BaseManaConversionMod"
  },
  IntValues = {
      [391]="WardLevel",
      [392]="ArmorSlots",
      [393]="ArmorWeightClass",
      [394]="GearMaxStamina",
      [395]="GearMaxMana",
      [396]="CombatFocusTypeId",
      [397]="WeightClassReqAmount",
      [398]="ArmorStyle",
      [399]="WeaponSubtype",
      [400]="ArmorPatchAmount",
      [401]="SigilTrinketColor",
      [404]="SigilTrinketMaxTier",
      [405]="SigilTrinketElement",
      [406]="SigilTrinketBonusStat",
      [407]="SigilTrinketBonusStatAmount",
      [408]="JewelSockets",
      [409]="GearStrength",
      [410]="GearEndurance",
      [411]="GearCoordination",
      [412]="GearQuickness",
      [413]="GearFocus",
      [414]="GearSelf",
      [415]="GearLifesteal",
      [416]="GearSelfHarm",
      [417]="GearThreatGain",
      [418]="GearThreatReduction",
      [419]="GearElementalWard",
      [420]="GearPhysicalWard",
      [421]="GearMagicFind",
      [422]="GearBlock",
      [423]="GearItemManaUsage",
      [424]="GearThorns",
      [425]="GearVitalsTransfer",
      [426]="GearRedFury",
      [427]="GearSelflessness",
      [428]="GearVipersStrike",
      [429]="GearFamiliarity",
      [430]="GearBravado",
      [431]="GearHealthToStamina",
      [432]="GearHealthToMana",
      [433]="GearExperienceGain",
      [434]="GearManasteal",
      [435]="GearBludgeon",
      [436]="GearPierce",
      [437]="GearSlash",
      [438]="GearFire",
      [439]="GearFrost",
      [440]="GearAcid",
      [441]="GearLightning",
      [442]="GearHealBubble",
      [443]="GearCompBurn",
      [444]="GearPyrealFind",
      [445]="GearNullification",
      [446]="GearWardPen",
      [447]="GearStaminasteal",
      [448]="GearHardenedDefense",
      [449]="GearReprisal",
      [450]="GearElementalist",
      [451]="BaseArmor",
      [452]="BaseDamage",
      [453]="BaseWard",
      [454]="BaseWeaponTime",
      [455]="BaseMaxMana",
      [456]="ItemSpellId",
      [457]="CombatFocusAttributeSpellRemoved",
      [458]="CombatFocusAttributeSpellAdded",
      [459]="CombatFocusSkillSpellRemoved",
      [460]="CombatFocusSkillSpellAdded",
      [461]="StackableSpellType",
      [462]="NearbyPlayerScalingThreshold",
      [463]="NearbyPlayerScalingExtraPlayersPerAdd",
      [464]="NearbyPlayerScalingAddWcid",
      [465]="RemainingConfirmations",
      [466]="SigilTrinketType",
      [467]="TrophyQuality",
      [468]="AmmoEffect",
      [469]="AmmoEffectUsesRemaining",
      [470]="AltCurrencyValue",
      [471]="GearYellowFury",
      [472]="GearBlueFury",
      [473]="NoCompsRequiredForMagicSchool",
      [474]="JewelSocket1Material",
      [475]="JewelSocket1Quality",
      [476]="JewelSocket2Material",
      [477]="JewelSocket2Quality",
      [478]="JewelSocket3Material",
      [479]="JewelSocket3Quality",
      [480]="JewelSocket4Material",
      [481]="JewelSocket4Quality",
      [482]="JewelSocket5Material",
      [483]="JewelSocket5Quality",
      [484]="JewelSocket6Material",
      [485]="JewelSocket6Quality",
      [486]="JewelSocket7Material",
      [487]="JewelSocket7Quality",
      [488]="JewelSocket8Material",
      [489]="JewelSocket8Quality",
      [490]="JewelSocket9Material",
      [491]="JewelSocket9Quality",
      [492]="JewelSocket10Material",
      [493]="JewelSocket10Quality",
      [494]="JewelMaterialType",
      [495]="JewelQuality",
      [496]="GearToughness",
      [497]="GearResistance",
      [498]="GearSlashBane",
      [499]="GearBludgeonBane",
      [500]="GearPierceBane",
      [501]="GearAcidBane",
      [502]="GearFireBane",
      [503]="GearFrostBane",
      [504]="GearLightningBane",
      [505]="CombatFocusSkill2SpellRemoved",
      [506]="CombatFocusSkill2SpellAdded",
      [507]="CombatFocusNumSkillsRemoved",
      [508]="CombatFocusNumSkillsAdded",
      [509]="StaminaOverTime",
      [510]="ManaOverTime",
      [511]="MonsterRank",
      [512]="CombatFocusSkill3SpellRemoved",
      [513]="CombatFocusSkill3SpellAdded",
      [514]="CombatFocusPrestigeVersionId",
      [10007]="Tier"
    },
    StringValues = {
    [9010]="LegacyJewelSocketString1",
    [9011]="LegacyJewelSocketString2",
    [9012]="CacheLog",
    [9013]="AllegianceLog",
    [9014]="CorpseLog"
    }
  }

  return M